import json
import os
import sys
from pathlib import Path
from unittest.mock import MagicMock, patch

import pytest

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

import bot.ai_bridge
from bot.ai_bridge import (
    MODE_PROMPTS,
    _is_code_request,
    _is_heavy_reasoning,
    _selected_mode,
    append_session_turn,
    clear_session,
    get_session_turns,
    send_to_antigravity_and_wait,
)
from bot.ui import (
    chat_action_keyboard,
    format_latex_math,
    mode_keyboard,
    model_selection_keyboard,
    render_assistant_text,
)
from llm_router import InferenceResult, InferenceStatus


@pytest.fixture(autouse=True)
def disable_activity_logging(monkeypatch):
    monkeypatch.setattr(bot.ai_bridge, "log_llm_call", MagicMock())


def test_format_latex_math_fractions_and_roots():
    text = r"The solution is \frac{a + b}{2c} and \sqrt{x^2 + y^2}."
    formatted = format_latex_math(text)
    assert "(a + b)/(2c)" in formatted
    assert "√(x² + y²)" in formatted


def test_format_latex_math_symbols_and_greek():
    text = r"\int_0^\infty f(x) dx \le \sum_{i=1}^n \alpha_i \cdot \beta_i \approx \Delta"
    formatted = format_latex_math(text)
    assert "∫" in formatted
    assert "∞" in formatted
    assert "≤" in formatted
    assert "∑" in formatted
    assert "α" in formatted
    assert "β" in formatted
    assert "≈" in formatted
    assert "Δ" in formatted


def test_format_latex_math_delimiters_stripped():
    text = r"$$E = mc^2$$ and $x \ge 0$"
    formatted = format_latex_math(text)
    assert "$$" not in formatted
    assert "$" not in formatted
    assert "E = mc²" in formatted
    assert "x ≥ 0" in formatted


def test_render_assistant_text_preserves_code_while_formatting_math():
    raw = "Formula:\n$$f(x) = x^2$$\n\nCode:\n```python\nx = 2**2\n```"
    rendered = render_assistant_text(raw)
    assert "f(x) = x²" in rendered
    assert "x = 2**2" in rendered
    assert "<pre>" in rendered


def test_chat_action_keyboard_callbacks():
    markup = chat_action_keyboard("123")
    callbacks = [btn.callback_data for row in markup.inline_keyboard for btn in row]
    assert "chat_act:simpler:123" in callbacks
    assert "chat_act:testme:123" in callbacks
    assert "chat_act:regen:123" in callbacks
    assert all(len(c.encode("utf-8")) <= 64 for c in callbacks)


def test_mode_keyboard_structure():
    markup = mode_keyboard("tutor")
    buttons = {btn.callback_data: btn.text for row in markup.inline_keyboard for btn in row}
    assert "mode:set:tutor" in buttons
    assert "✓" in buttons["mode:set:tutor"]
    assert "mode:set:quick" in buttons
    assert "mode:set:drill" in buttons
    assert "mode:set:default" in buttons


def test_model_selection_keyboard_structure():
    markup = model_selection_keyboard("auto")
    buttons = {btn.callback_data: btn.text for row in markup.inline_keyboard for btn in row}
    assert "model:set:auto" in buttons
    assert "✓" in buttons["model:set:auto"]
    assert "model:set:local" in buttons
    assert "model:set:llama3.3" in buttons
    assert "model:set:qwen-coder" in buttons


def test_session_history_lifecycle(tmp_path, monkeypatch):
    monkeypatch.setattr(bot.ai_bridge, "CHAT_HISTORY_DIR", tmp_path)

    chat_id = 99999
    turns = get_session_turns(chat_id)
    assert turns == []

    append_session_turn(chat_id, "What is Newton's second law?", "F = ma\n\n_(Generated by: local)_")
    turns = get_session_turns(chat_id)
    assert len(turns) == 1
    assert turns[0]["user"] == "What is Newton's second law?"
    assert turns[0]["assistant"] == "F = ma"  # Generation badge stripped for clean memory

    append_session_turn(chat_id, "Can you give an example?", "Pushing a cart.")
    turns = get_session_turns(chat_id)
    assert len(turns) == 2

    assert clear_session(chat_id) is True
    turns = get_session_turns(chat_id)
    assert turns == []


def test_intent_detection():
    assert _is_code_request("Can you fix this python function: def add(a, b): return a + b") is True
    assert _is_code_request("What is the capital of France?") is False
    assert _is_heavy_reasoning("Derive the step-by-step calculus formula for arc length") is True
    assert _is_heavy_reasoning("hello") is False


@pytest.mark.asyncio
async def test_smart_auto_routes_code_to_qwen_coder():
    async def _inline_to_thread(func, /, *args, **kwargs):
        return func(*args, **kwargs)

    with patch("bot.ai_bridge.load_state", return_value={"user_models": {"123": "auto"}}), \
         patch("bot.ai_bridge.detect_topic", return_value="programming"), \
         patch("bot.ai_bridge.check_pii", return_value=(True, "code", [])), \
         patch(
             "bot.ai_bridge.call_agy_result",
             return_value=InferenceResult.success("def solve(): pass", provider="agy", model="Gemini 3.7 Flash (Low)"),
         ) as mock_agy, \
         patch("bot.ai_bridge.asyncio.to_thread", new=_inline_to_thread):

        resp = await send_to_antigravity_and_wait(
            "Write a python script to parse CSV files",
            chat_id=123,
            cloud_consent=True,
        )
        assert "def solve(): pass" in resp
        assert "Google" in resp
        assert mock_agy.call_args.kwargs["model"] == "flash"


@pytest.mark.asyncio
async def test_smart_auto_routes_pro_for_heavy_math():
    async def _inline_to_thread(func, /, *args, **kwargs):
        return func(*args, **kwargs)

    with patch("bot.ai_bridge.load_state", return_value={"user_models": {"123": "auto"}}), \
         patch("bot.ai_bridge.detect_topic", return_value="calculus"), \
         patch("bot.ai_bridge.check_pii", return_value=(True, "math", [])), \
         patch(
             "bot.ai_bridge.call_agy_result",
             return_value=InferenceResult.success("∫ x dx = x^2/2", provider="agy", model="Gemini 3.1 Pro (Low)"),
         ) as mock_agy, \
         patch("bot.ai_bridge.asyncio.to_thread", new=_inline_to_thread):

        resp = await send_to_antigravity_and_wait(
            "Derive the integral step-by-step",
            chat_id=123,
            cloud_consent=True,
        )
        assert "Google" in resp
        assert mock_agy.call_args.kwargs["model"] == "pro"

